/* Generated from cardv .data:0x110dc20 -- see cardv-re.md §3.1.
   Regenerate with: python3 tools/cfgapply/gen_table.py > settings_table.h */
struct cfg_ent { const char *key; int id; };
static const struct cfg_ent CFG_TABLE[] = {
    { "Resolution", 0x1a },
    { "Video Bitrate", 0xa1 },
    { "Dewarp Front Cam", 0xeb },
    { "Loop Recording", 0x22 },
    { "Record Audio", 0x24 },
    { "G-sensor", 0x95 },
    { "Time-lapse Recording", 0x26 },
    { "Interior Cam Fisheye Mode", 0xd9 },
    { "IR LED", 0x27 },
    { "Interior Camera", 0xd2 },
    { "Rear Camera", 0xe0 },
    { "Multiplex Video", 0xde },
    { "Live Video Source", 0x11 },
    { "Privacy Mode", 0xce },
    { "Vehicle Battery Protection", 0xda },
    { "Cut-off time", 0x9a },
    { "Cut-off Voltage", 0xdc },
    { "Cut-off BP100 Capacity", 0xe9 },
    { "Parking Mode", 0x97 },
    { "Hybrid Parking mode", 0xdd },
    { "Enter Parking Mode Timer", 0x99 },
    { "Parking G-sensor", 0x96 },
    { "Parking Motion Detection", 0x98 },
    { "Parking GPS", 0xc7 },
    { "Parking HDR", 0xcb },
    { "Parking Recording Storage", 0xd7 },
    { "Geofencing", 0xe2 },
    { "Parking Impact Notification", 0xe3 },
    { "Backup Impact Parking Videos", 0xe4 },
    { "Low Power Impact Recording", 0xec },
    { "HDR Front", 0x1d },
    { "HDR Rear", 0xca },
    { "HDR Interior", 0xc9 },
    { "EV Front", 0xa3 },
    { "EV Interior", 0xa4 },
    { "EV Rear", 0xa5 },
    { "Date Stamp", 0xb2 },
    { "GPS Speed Stamp", 0xb5 },
    { "GPS Coordinates Stamp", 0xb6 },
    { "Custom Stamp", 0xb7 },
    { "License Plate Stamp", 0xb8 },
    { "Logo Stamp", 0xb9 },
    { "Brand Model Stamp", 0xa7 },
    { "Resolution Stamp", 0xc6 },
    { "Vehicle Voltage Stamp", 0xe1 },
    { "Battery pack Capacity Stamp", 0xed },
    { "Stamp Text Color", 0xcf },
    { "Interior Image Rotate", 0xac },
    { "Interior Image Mirror", 0xaf },
    { "Rear Image Rotate", 0xab },
    { "Rear Image Mirror", 0xae },
    { "Wi-Fi", 0x81 },
    { "Wi-Fi Frequency", 0xa9 },
    { "Time Zone", 0x91 },
    { "Time Format", 0x41 },
    { "Daylight Saving", 0xa0 },
    { "Boot Delay", 0xa8 },
    { "Driving Recording Storage", 0xc3 },
    { "Beep Sound", 0x38 },
    { "Voice Notification", 0x9d },
    { "Voice Notification Volume", 0x71 },
    { "Voice Control", 0x9f },
    { "GPS", 0x92 },
    { "Speed Units", 0x93 },
    { "Screen Saver", 0x6d },
    { "Frequency", 0x3a },
    { "Format Reminder", 0x9c },
    { "Mic Button", 0xbf },
    { "Action Button", 0xc0 },
    { "Front LED", 0xb1 },
    { "Rear LED", 0xd3 },
    { "Interior LED", 0xd4 },
    { "Front Parking LED", 0xb3 },
    { "Rear Parking LED", 0xd5 },
    { "Interior Parking LED", 0xd6 },
};
#define CFG_TABLE_N 75
